services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: URI-BACKEND
      POSTGRES_USER: postgres
      POSTGRES_DB: url_shortener
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api
    restart: unless-stopped
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      # Sobrescreve o DB_HOST do .env para apontar pro container postgres
      DB_HOST: postgres
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
